version: '3.8'
services:
  proxypool_mysql:
    image: mysql:5.7.34
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    restart: always
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    command:
      --character-set-server=utf8mb4
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
      --max_connections=3600
    networks:
      - app-network

  proxypool_proxypool:
    image: proxypool:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - proxypool_mysql
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./conf/config.yaml:/app/conf/config.yaml
    networks:
      - app-network

networks:
  # 一个具体网络的条目名称
  app-network:
    # 网络名称，默认为"工程名称_网络条目名称"
    name: app-network
    # 网络模式，默认为 bridge
    driver: bridge
