# server configuration
system:
  appName: ProxyPool
  # service listening address
  httpAddr: 0.0.0.0
  # service listening port
  httpPort: 3000

# mysql
database:
  host: proxypool_mysql
  port: 3306
  dbName: IpProxyPool
  username: root
  password: 'P@ssw0rd'


# logger configuration
log:
  filePath: logs
  fileName: run.log
  # Either "info", "warn", "error", "debug", default is "info"
  level: info
  # Can be "console" and "file", default is "console"
  # Use comma to separate multiple modes, e.g. "console, file"
  mode: console